INSERT INTO Cities (name, countryCode, population) VALUES ('Zunyi', 'ch', 6127009);
INSERT INTO Cities (name, countryCode, population) VALUES ('Zhengzhou', 'ch', 4122087);
INSERT INTO Cities (name, countryCode, population) VALUES ('San Diego', 'us', 1394928);
INSERT INTO Cities (name, countryCode, population) VALUES ('Basra', 'iz', 2750000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kiev', 'up', 2908703);
INSERT INTO Cities (name, countryCode, population) VALUES ('Paris', 'fr', 2229621);
INSERT INTO Cities (name, countryCode, population) VALUES ('Rio de Janeiro', 'br', 6429923);
INSERT INTO Cities (name, countryCode, population) VALUES ('Monterrey', 'mx', 1130960);
INSERT INTO Cities (name, countryCode, population) VALUES ('Johannesburg', 'sf', 4434827);
INSERT INTO Cities (name, countryCode, population) VALUES ('Fortaleza', 'br', 2609716);
INSERT INTO Cities (name, countryCode, population) VALUES ('Zhongshan', 'ch', 3121275);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ulsan', 'ks', 1163690);
INSERT INTO Cities (name, countryCode, population) VALUES ('Abuja', 'ni', 1235880);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bhopal', 'in', 1798218);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shenzhen', 'ch', 8378900);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bangkok', 'th', 8750600);
INSERT INTO Cities (name, countryCode, population) VALUES ('Santiago', 'ci', 5743719);
INSERT INTO Cities (name, countryCode, population) VALUES ('Chennai', 'in', 8570880);
INSERT INTO Cities (name, countryCode, population) VALUES ('Delhi', 'in', 21678794);
INSERT INTO Cities (name, countryCode, population) VALUES ('Campinas', 'br', 1164098);
INSERT INTO Cities (name, countryCode, population) VALUES ('Incheon', 'ks', 2978367);
INSERT INTO Cities (name, countryCode, population) VALUES ('Baghdad', 'iz', 7180889);
INSERT INTO Cities (name, countryCode, population) VALUES ('Maracaibo', 've', 1599940);
INSERT INTO Cities (name, countryCode, population) VALUES ('Taipei', 'tw', 2704974);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hamburg', 'gm', 1787408);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ahmedabad', 'in', 5570585);
INSERT INTO Cities (name, countryCode, population) VALUES ('Jeddah', 'sa', 3456259);
INSERT INTO Cities (name, countryCode, population) VALUES ('Fukuoka', 'ja', 1483052);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bogotá', 'co', 7878783);
INSERT INTO Cities (name, countryCode, population) VALUES ('Addis Ababa', 'et', 3103673);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tabriz', 'ir', 1733033);
INSERT INTO Cities (name, countryCode, population) VALUES ('Chittagong', 'bg', 2581643);
INSERT INTO Cities (name, countryCode, population) VALUES ('Nagpur', 'in', 2405665);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ankara', 'tu', 5271000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Yekaterinburg', 'rs', 1428042);
INSERT INTO Cities (name, countryCode, population) VALUES ('Yaoundé', 'cm', 2440462);
INSERT INTO Cities (name, countryCode, population) VALUES ('Rome', 'it', 2877215);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tangshan', 'ch', 3187171);
INSERT INTO Cities (name, countryCode, population) VALUES ('Accra', 'gh', 2070463);
INSERT INTO Cities (name, countryCode, population) VALUES ('Surat', 'in', 4462002);
INSERT INTO Cities (name, countryCode, population) VALUES ('New Taipei City', 'tw', 3954929);
INSERT INTO Cities (name, countryCode, population) VALUES ('Harbin', 'ch', 4280701);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kanpur', 'in', 2768057);
INSERT INTO Cities (name, countryCode, population) VALUES ('Peshawar', 'pk', 1970042);
INSERT INTO Cities (name, countryCode, population) VALUES ('Alexandria', 'eg', 4616625);
INSERT INTO Cities (name, countryCode, population) VALUES ('Casablanca', 'mo', 5117832);
INSERT INTO Cities (name, countryCode, population) VALUES ('Brisbane', 'as', 1180285);
INSERT INTO Cities (name, countryCode, population) VALUES ('Cairo', 'eg', 10230350);
INSERT INTO Cities (name, countryCode, population) VALUES ('Osaka', 'ja', 2691742);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shenyang', 'ch', 8106171);
INSERT INTO Cities (name, countryCode, population) VALUES ('Cologne', 'gm', 1057327);
INSERT INTO Cities (name, countryCode, population) VALUES ('Milan', 'it', 1359905);
INSERT INTO Cities (name, countryCode, population) VALUES ('London', 'uk', 8787892);
INSERT INTO Cities (name, countryCode, population) VALUES ('Medan', 'id', 2097610);
INSERT INTO Cities (name, countryCode, population) VALUES ('Visakhapatnam', 'in', 2035922);
INSERT INTO Cities (name, countryCode, population) VALUES ('Davao City', 'rp', 1632991);
INSERT INTO Cities (name, countryCode, population) VALUES ('Douala', 'cm', 2446945);
INSERT INTO Cities (name, countryCode, population) VALUES ('İzmir', 'tu', 4168000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shiraz', 'ir', 1869001);
INSERT INTO Cities (name, countryCode, population) VALUES ('Caracas', 've', 1943901);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kwangju', 'ks', 1477780);
INSERT INTO Cities (name, countryCode, population) VALUES ('Auckland', 'nz', 1495000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Makassar', 'id', 1338633);
INSERT INTO Cities (name, countryCode, population) VALUES ('Guadalajara', 'mx', 1495189);
INSERT INTO Cities (name, countryCode, population) VALUES ('Rawalpindi', 'pk', 2098231);
INSERT INTO Cities (name, countryCode, population) VALUES ('Oran', 'ag', 1560329);
INSERT INTO Cities (name, countryCode, population) VALUES ('Sydney', 'as', 208374);
INSERT INTO Cities (name, countryCode, population) VALUES ('Isfahan', 'ir', 2243249);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kolkata', 'in', 4486679);
INSERT INTO Cities (name, countryCode, population) VALUES ('Curitiba', 'br', 1879355);
INSERT INTO Cities (name, countryCode, population) VALUES ('Vienna', 'au', 1863881);
INSERT INTO Cities (name, countryCode, population) VALUES ('Seoul', 'ks', 10197604);
INSERT INTO Cities (name, countryCode, population) VALUES ('Singapore', 'sn', 5535000);
INSERT INTO Cities (name, countryCode, population) VALUES ('New York City', 'us', 8537673);
INSERT INTO Cities (name, countryCode, population) VALUES ('Moscow', 'rs', 12197596);
INSERT INTO Cities (name, countryCode, population) VALUES ('Guangzhou', 'ch', 14043500);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hefei', 'ch', 3352076);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kuala Lumpur', 'my', 1768000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Berlin', 'gm', 3517424);
INSERT INTO Cities (name, countryCode, population) VALUES ('Rosario', 'ar', 1193605);
INSERT INTO Cities (name, countryCode, population) VALUES ('Los Angeles', 'us', 3884307);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tehran', 'ir', 8154051);
INSERT INTO Cities (name, countryCode, population) VALUES ('Palembang', 'id', 1708413);
INSERT INTO Cities (name, countryCode, population) VALUES ('Astana', 'kz',  1029556);
INSERT INTO Cities (name, countryCode, population) VALUES ('San Antonio', 'us', 1469845);
INSERT INTO Cities (name, countryCode, population) VALUES ('Karachi', 'pk', 14910352);
INSERT INTO Cities (name, countryCode, population) VALUES ('Caloocan', 'rp', 1583978);
INSERT INTO Cities (name, countryCode, population) VALUES ('Xiamen', 'ch', 3531347);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ibadan', 'ni', 1338659);
INSERT INTO Cities (name, countryCode, population) VALUES ('Lucknow', 'in', 2815601);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kano', 'ni', 2153225);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kharkiv', 'up', 1449414);
INSERT INTO Cities (name, countryCode, population) VALUES ('Cape Town', 'sf', 3740026);
INSERT INTO Cities (name, countryCode, population) VALUES ('Foshan', 'ch', 6151622);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hangzhou', 'ch', 3560391);
INSERT INTO Cities (name, countryCode, population) VALUES ('Fuzhou', 'ch', 7115369);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ningbo', 'ch', 3491597);
INSERT INTO Cities (name, countryCode, population) VALUES ('Giza', 'eg', 4239988);
INSERT INTO Cities (name, countryCode, population) VALUES ('Saitama', 'ja', 1226656);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hyderabad', 'pk', 1732693);
INSERT INTO Cities (name, countryCode, population) VALUES ('Quezon City', 'rp', 2936116);
INSERT INTO Cities (name, countryCode, population) VALUES ('Madrid', 'sp', 3207247);
INSERT INTO Cities (name, countryCode, population) VALUES ('Guatemala City', 'gt', 2110100);
INSERT INTO Cities (name, countryCode, population) VALUES ('Baku', 'aj', 3202300);
INSERT INTO Cities (name, countryCode, population) VALUES ('Brasília', 'br', 2556149);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bandung', 'id', 2575478);
INSERT INTO Cities (name, countryCode, population) VALUES ('Khartoum', 'su', 3639598);
INSERT INTO Cities (name, countryCode, population) VALUES ('Busan', 'ks', 3510833);
INSERT INTO Cities (name, countryCode, population) VALUES ('Chaozhou', 'ch', 2669844);
INSERT INTO Cities (name, countryCode, population) VALUES ('Mexico City', 'mx', 8974724);
INSERT INTO Cities (name, countryCode, population) VALUES ('Istanbul', 'tu', 14025000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Dallas', 'us', 1317929);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hanoi', 'vm', 6844100);
INSERT INTO Cities (name, countryCode, population) VALUES ('Mashhad', 'ir', 3312090);
INSERT INTO Cities (name, countryCode, population) VALUES ('Dar es Salaam', 'tz', 4364541);
INSERT INTO Cities (name, countryCode, population) VALUES ('Porto Alegre', 'br', 1476867);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bengaluru', 'in', 8692500);
INSERT INTO Cities (name, countryCode, population) VALUES ('Patna', 'in', 1683200);
INSERT INTO Cities (name, countryCode, population) VALUES ('Manila', 'rp', 1780148);
INSERT INTO Cities (name, countryCode, population) VALUES ('Lahore', 'pk', 11126285);
INSERT INTO Cities (name, countryCode, population) VALUES ('Calgary', 'ca', 1235171);
INSERT INTO Cities (name, countryCode, population) VALUES ('Fez', 'mo', 1112072);
INSERT INTO Cities (name, countryCode, population) VALUES ('Recife', 'br', 1555039);
INSERT INTO Cities (name, countryCode, population) VALUES ('Dongguan', 'ch', 8220207);
INSERT INTO Cities (name, countryCode, population) VALUES ('Lanzhou', 'ch', 2177130);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shantou', 'ch', 5391028);
INSERT INTO Cities (name, countryCode, population) VALUES ('Durban', 'sf', 3442361);
INSERT INTO Cities (name, countryCode, population) VALUES ('Jaipur', 'in', 3073350);
INSERT INTO Cities (name, countryCode, population) VALUES ('Semarang', 'id', 1555984);
INSERT INTO Cities (name, countryCode, population) VALUES ('Quanzhou', 'ch', 8128533);
INSERT INTO Cities (name, countryCode, population) VALUES ('Faisalabad', 'pk', 3203846);
INSERT INTO Cities (name, countryCode, population) VALUES ('Vijayawada', 'in', 1491202);
INSERT INTO Cities (name, countryCode, population) VALUES ('Gujranwala', 'pk', 2027001);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tijuana', 'mx', 1696923);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hong Kong', 'ch', 7274900);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shijiazhuang', 'ch', 4303700);
INSERT INTO Cities (name, countryCode, population) VALUES ('Toronto', 'ca', 2929886);
INSERT INTO Cities (name, countryCode, population) VALUES ('Algiers', 'ag', 3415811);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tokyo', 'ja', 13513734);
INSERT INTO Cities (name, countryCode, population) VALUES ('Islamabad', 'pk', 1014825);
INSERT INTO Cities (name, countryCode, population) VALUES ('Nagoya', 'ja', 2296014);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tunis', 'ts', 1056247);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tripoli', 'ly', 1126000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Nairobi', 'ke', 3138369);
INSERT INTO Cities (name, countryCode, population) VALUES ('Montreal', 'ca', 1649519);
INSERT INTO Cities (name, countryCode, population) VALUES ('Bucharest', 'ro', 1883425);
INSERT INTO Cities (name, countryCode, population) VALUES ('Beijing', 'ch', 21516000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Cali', 'co', 2400653);
INSERT INTO Cities (name, countryCode, population) VALUES ('Birmingham', 'uk', 1111300);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kobe', 'ja', 1536499);
INSERT INTO Cities (name, countryCode, population) VALUES ('Lima', 'pe', 8852000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Belo Horizonte', 'br', 2502557);
INSERT INTO Cities (name, countryCode, population) VALUES ('Córdoba', 'ar', 1330023);
INSERT INTO Cities (name, countryCode, population) VALUES ('Surabaya', 'id', 2765487);
INSERT INTO Cities (name, countryCode, population) VALUES ('Sofia', 'bu', 1260120);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kaohsiung', 'tw', 2778918);
INSERT INTO Cities (name, countryCode, population) VALUES ('Mumbai', 'in', 21247844);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tianjin', 'ch', 12784000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Shanghai', 'ch', 24256800);
INSERT INTO Cities (name, countryCode, population) VALUES ('Pune', 'in', 3115431);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ho Chi Minh City', 'vm', 8426100);
INSERT INTO Cities (name, countryCode, population) VALUES ('Saint Petersburg', 'rs', 5191690);
INSERT INTO Cities (name, countryCode, population) VALUES ('Hiroshima', 'ja', 1196274);
INSERT INTO Cities (name, countryCode, population) VALUES ('São Paulo', 'br', 12038175);
INSERT INTO Cities (name, countryCode, population) VALUES ('Ekurhuleni', 'sf', 3178470);
INSERT INTO Cities (name, countryCode, population) VALUES ('Montevideo', 'uy', 1305082);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tashkent', 'uz', 2309600);
INSERT INTO Cities (name, countryCode, population) VALUES ('Luanda', 'ao', 2825311);
INSERT INTO Cities (name, countryCode, population) VALUES ('Wenzhou', 'ch', 9175000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Buenos Aires', 'ar', 3054300);
INSERT INTO Cities (name, countryCode, population) VALUES ('Daejeon', 'ks', 1535028);
INSERT INTO Cities (name, countryCode, population) VALUES ('Changchun', 'ch', 3815270);
INSERT INTO Cities (name, countryCode, population) VALUES ('Omsk', 'rs', 1154116);
INSERT INTO Cities (name, countryCode, population) VALUES ('Wuhan', 'ch', 6886253);
INSERT INTO Cities (name, countryCode, population) VALUES ('Daegu', 'ks', 2492994);
INSERT INTO Cities (name, countryCode, population) VALUES ('Barranquilla', 'co', 1386865);
INSERT INTO Cities (name, countryCode, population) VALUES ('Munich', 'gm', 1450381);
INSERT INTO Cities (name, countryCode, population) VALUES ('Guayaquil', 'ec', 3600000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Qingdao', 'ch', 6188100);
INSERT INTO Cities (name, countryCode, population) VALUES ('Tainan', 'tw', 1885252);
INSERT INTO Cities (name, countryCode, population) VALUES ('Dhaka', 'bg', 19840000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Taichung', 'tw', 2752413);
INSERT INTO Cities (name, countryCode, population) VALUES ('Budapest', 'hu', 1759407);
INSERT INTO Cities (name, countryCode, population) VALUES ('Novosibirsk', 'rs', 1567087);
INSERT INTO Cities (name, countryCode, population) VALUES ('Salvador', 'br', 2902927);
INSERT INTO Cities (name, countryCode, population) VALUES ('Jakarta', 'id', 10075310);
INSERT INTO Cities (name, countryCode, population) VALUES ('Karaj', 'ir', 1973470);
INSERT INTO Cities (name, countryCode, population) VALUES ('Barcelona', 'sp', 1604555);
INSERT INTO Cities (name, countryCode, population) VALUES ('Changsha', 'ch', 7044118);
INSERT INTO Cities (name, countryCode, population) VALUES ('Melbourne', 'as', 135959);
INSERT INTO Cities (name, countryCode, population) VALUES ('Minsk', 'bo', 1959781);
INSERT INTO Cities (name, countryCode, population) VALUES ('Phoenix', 'us', 1563025);
INSERT INTO Cities (name, countryCode, population) VALUES ('Suzhou', 'ch', 8265050);
INSERT INTO Cities (name, countryCode, population) VALUES ('Almaty', 'kz', 1792549);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kawasaki', 'ja', 1496035);
INSERT INTO Cities (name, countryCode, population) VALUES ('Quito', 'ec', 2671191);
INSERT INTO Cities (name, countryCode, population) VALUES ('Houston', 'us', 2489558);
INSERT INTO Cities (name, countryCode, population) VALUES ('Dalian', 'ch', 2146099);
INSERT INTO Cities (name, countryCode, population) VALUES ('Chengdu', 'ch', 16044700);
INSERT INTO Cities (name, countryCode, population) VALUES ('Belgrade', 'ri', 1166763);
INSERT INTO Cities (name, countryCode, population) VALUES ('Riyadh', 'sa', 5676621);
INSERT INTO Cities (name, countryCode, population) VALUES ('Philadelphia', 'us', 1567872);
INSERT INTO Cities (name, countryCode, population) VALUES ('Jinan', 'ch', 2009273);
INSERT INTO Cities (name, countryCode, population) VALUES ('Nanjing', 'ch', 8230000);
INSERT INTO Cities (name, countryCode, population) VALUES ('Rostov-on-Don', 'rs', 1119900);
INSERT INTO Cities (name, countryCode, population) VALUES ('Medellin', 'co', 2441123);
INSERT INTO Cities (name, countryCode, population) VALUES ('Suwon', 'ks', 1202310);
INSERT INTO Cities (name, countryCode, population) VALUES ('Lagos', 'ni', 16060303);
INSERT INTO Cities (name, countryCode, population) VALUES ('Chicago', 'us', 2695598);
INSERT INTO Cities (name, countryCode, population) VALUES ('Yokohama', 'ja', 3726167);
INSERT INTO Cities (name, countryCode, population) VALUES ('Santa Cruz de la Sierra', 'bl', 1453549);
INSERT INTO Cities (name, countryCode, population) VALUES ('Kyoto', 'ja', 1474570);
INSERT INTO Cities (name, countryCode, population) VALUES ('Nizhny Novgorod', 'rs', 1250619);
INSERT INTO Cities (name, countryCode, population) VALUES ('Sapporo', 'ja', 1918096);
INSERT INTO Cities (name, countryCode, population) VALUES ('Warsaw', 'pl', 1753977);
