INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Lupghar Sar', 'pk', 23622);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Labuche Kang', 'ch', 24170);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Baintha Brakk', 'pk', 23901);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Sherpi Kangri', 'pk', 24213);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Saser Kangri II E', 'in', 24649);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Makalu', 'ch', 27838);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Apsarasas Kangri', 'ch', 23770);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Changtse', 'ch', 24747);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Rimo III', 'in', 23730);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Skyang Kangri', 'ch', 24754);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Siguang Ri', 'ch', 23980);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Shishapangma', 'ch', 26335);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Momhil Sar', 'pk', 24324);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Diran', 'pk', 23839);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Abi Gamin', 'ch', 24131);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Chogolisa', 'pk', 25148);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Noshaq', 'pk', 24580);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Jomolhari', 'ch', 24035);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Mamostong Kangri', 'in', 24659);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gongga Shan', 'ch', 24790);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kongur Tiube', 'ch', 24705);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Yangra', 'ch', 24350);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gangkhar Puensum', 'ch', 24836);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Chongtar', 'ch', 23999);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Jengish Chokusu', 'ch', 24406);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kamet', 'in', 25446);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Chomo Lonzo', 'ch', 25604);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Pumari Chhish', 'pk', 24580);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Saltoro Kangri', 'pk', 25400);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Porong Ri', 'ch', 23924);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Sunanda Devi', 'in', 24390);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Yukshin Gardan Sar', 'pk', 24505);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Istor-o-Nal', 'pk', 24288);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Sia Kangri', 'ch', 24350);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Molamenqing', 'ch', 25272);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Tongshanjiabu', 'ch', 23645);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kangchenjunga', 'in', 28169);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gasherbrum I', 'ch', 26509);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Passu Sar', 'pk', 24528);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Namcha Barwa', 'ch', 25531);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Khunyang Chhish', 'pk', 25666);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Yutmaru Sar', 'pk', 23894);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('K12', 'pk', 24370);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Saser Kangri I', 'in', 25171);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('K2', 'ch', 28251);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Nanda Devi', 'in', 25643);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Rimo I', 'in', 24229);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gasherbrum III', 'ch', 26070);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Teram Kangri I', 'ch', 24482);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Ultar', 'pk', 24239);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Haramosh Peak', 'pk', 24308);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Khartaphu', 'ch', 23665);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Skil Brum', 'pk', 24311);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Distaghil Sar', 'pk', 25866);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gyala Peri', 'ch', 23930);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Teram Kangri III', 'ch', 24219);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Baltoro Kangri', 'pk', 23990);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Saraghrar', 'pk', 24111);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Muztagh Ata', 'ch', 24636);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gurla Mandhata', 'ch', 25243);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Labuche Kang III', 'ch', 23786);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Mana Peak', 'in', 23858);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kangpenqing', 'ch', 23888);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Tirich Mir', 'pk', 25289);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Malubiting', 'pk', 24469);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kangphu Kang', 'ch', 23635);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Trivor', 'pk', 24859);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Lhotse', 'ch', 27940);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kongur Tagh', 'ch', 25095);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gyachung Kang', 'ch', 26089);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Nangpai Gosum', 'ch', 24114);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Singhi Kangri', 'ch', 23629);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Cho Oyu', 'ch', 26864);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Mukut Parbat', 'ch', 23760);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Mount Everest', 'ch', 29029);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('The Crown', 'ch', 23934);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Baltistan Peak', 'pk', 23891);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Jongsong Peak', 'ch', 24482);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Nanga Parbat', 'pk', 26660);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Ghent Kangri', 'pk', 24281);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Broad Peak', 'ch', 26414);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Kanjut Sar', 'pk', 25558);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gasherbrum II', 'ch', 26362);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Karjiang', 'ch', 23691);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Noijin Kangsang', 'ch', 23642);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Rakaposhi', 'pk', 25551);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Gasherbrum IV', 'pk', 26024);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Malangutti Sar', 'pk', 23645);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Muztagh Tower', 'ch', 23871);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Batura Sar', 'pk', 25574);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Shispare', 'pk', 24970);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Saser Kangri III', 'in', 24590);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Masherbrum', 'pk', 25659);
INSERT INTO Mountains (name, countryCode, elevation) VALUES ('Langtang Ri', 'ch', 23638);
